const reportsData = {
const reportsData =   "1": {
const reportsData =     "id": "1",
const reportsData =     "name": "系统健康度分析报告",
const reportsData =     "type": "health",
const reportsData =     "status": "published",
const reportsData =     "author": "系统管理员",
const reportsData =     "createdAt": "2024-06-15 10:30:00",
const reportsData =     "lastModified": "2024-06-15 14:20:00",
const reportsData =     "size": "2.5MB",
const reportsData =     "downloads": 156,
const reportsData =     "description": "本报告全面分析了系统的健康状况，包括服务可用性、性能指标、错误率等关键指标。通过多维度数据分析，为系统优化提供决策支持。报告涵盖了过去30天的运行数据，识别出关键问题并提供具体的改进建议。",
const reportsData =     "summary": {
const reportsData =       "totalServices": 45,
const reportsData =       "healthyServices": 42,
const reportsData =       "warningServices": 2,
const reportsData =       "criticalServices": 1,
const reportsData =       "overallScore": 93.3
const reportsData =     },
const reportsData =     "sections": [
const reportsData =       {
const reportsData =         "titleKey": "executiveSummary",
const reportsData =         "title": "执行摘要",
const reportsData =         "content": "系统整体健康状况良好，93.3%的服务运行正常。在监控的45个核心服务中，42个服务状态健康，2个服务存在性能警告，1个服务需要紧急处理。主要问题集中在通知服务的响应时间过长和支付服务的错误率偏高。建议优先处理通知服务的性能瓶颈，预计修复后系统整体评分可提升至96%以上。",
const reportsData =         "type": "summary",
const reportsData =         "keyMetrics": {
const reportsData =           "systemUptime": "99.2%",
const reportsData =           "avgResponseTime": "185ms",
const reportsData =           "errorRate": "0.23%",
const reportsData =           "throughput": "15.2K req/s",
const reportsData =           "activeUsers": "12,450",
const reportsData =           "peakConcurrency": "3,200"
const reportsData =         },
const reportsData =         "highlights": [
const reportsData =           "系统整体可用性达到99.2%，超过SLA要求的99%",
const reportsData =           "42个核心服务运行状态良好，占总数的93.3%",
const reportsData =           "通知服务存在性能瓶颈，响应时间超过1秒",
const reportsData =           "支付服务错误率偏高，需要紧急优化",
const reportsData =           "数据库连接池使用率78%，接近预警阈值"
const reportsData =         ]
const reportsData =       },
const reportsData =       {
const reportsData =         "titleKey": "serviceStatusAnalysis",
const reportsData =         "title": "服务状态详细分析",
const reportsData =         "content": "以下是各核心服务的详细运行状态分析，包括响应时间、错误率、可用性等关键指标。数据基于过去30天的监控记录。",
const reportsData =         "type": "analysis",
const reportsData =         "data": [
const reportsData =           {
const reportsData =             "service": "用户认证服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "85ms",
const reportsData =             "errorRate": "0.02%",
const reportsData =             "availability": "99.98%",
const reportsData =             "requests": "2.3M",
const reportsData =             "instances": 3,
const reportsData =             "cpuUsage": "45%",
const reportsData =             "memoryUsage": "62%",
const reportsData =             "lastIncident": "2024-06-01",
const reportsData =             "slaCompliance": "100%"
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "用户管理服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "120ms",
const reportsData =             "errorRate": "0.1%",
const reportsData =             "availability": "99.95%",
const reportsData =             "requests": "1.8M",
const reportsData =             "instances": 2,
const reportsData =             "cpuUsage": "38%",
const reportsData =             "memoryUsage": "55%",
const reportsData =             "lastIncident": "2024-05-28",
const reportsData =             "slaCompliance": "99.8%"
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "订单处理服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "95ms",
const reportsData =             "errorRate": "0.05%",
const reportsData =             "availability": "99.97%",
const reportsData =             "requests": "890K",
const reportsData =             "instances": 4,
const reportsData =             "cpuUsage": "52%",
const reportsData =             "memoryUsage": "68%",
const reportsData =             "lastIncident": "2024-05-15",
const reportsData =             "slaCompliance": "100%"
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "库存管理服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "110ms",
const reportsData =             "errorRate": "0.08%",
const reportsData =             "availability": "99.96%",
const reportsData =             "requests": "1.2M",
const reportsData =             "instances": 3,
const reportsData =             "cpuUsage": "41%",
const reportsData =             "memoryUsage": "59%",
const reportsData =             "lastIncident": "2024-06-05",
const reportsData =             "slaCompliance": "99.9%"
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "支付处理服务",
const reportsData =             "status": "warning",
const reportsData =             "responseTime": "280ms",
const reportsData =             "errorRate": "0.8%",
const reportsData =             "availability": "99.2%",
const reportsData =             "requests": "650K",
const reportsData =             "instances": 2,
const reportsData =             "cpuUsage": "75%",
const reportsData =             "memoryUsage": "82%",
const reportsData =             "lastIncident": "2024-06-12",
const reportsData =             "slaCompliance": "95.2%",
const reportsData =             "issues": [
const reportsData =               "第三方支付网关响应延迟",
const reportsData =               "数据库连接池耗尽",
const reportsData =               "内存泄漏导致频繁重启"
const reportsData =             ]
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "物流跟踪服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "150ms",
const reportsData =             "errorRate": "0.15%",
const reportsData =             "availability": "99.9%",
const reportsData =             "requests": "420K",
const reportsData =             "instances": 2,
const reportsData =             "cpuUsage": "35%",
const reportsData =             "memoryUsage": "48%",
const reportsData =             "lastIncident": "2024-05-20",
const reportsData =             "slaCompliance": "99.5%"
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "通知推送服务",
const reportsData =             "status": "critical",
const reportsData =             "responseTime": "1200ms",
const reportsData =             "errorRate": "5.2%",
const reportsData =             "availability": "95.8%",
const reportsData =             "requests": "3.1M",
const reportsData =             "instances": 3,
const reportsData =             "cpuUsage": "89%",
const reportsData =             "memoryUsage": "91%",
const reportsData =             "lastIncident": "2024-06-14",
const reportsData =             "slaCompliance": "85.3%",
const reportsData =             "issues": [
const reportsData =               "消息队列积压严重，处理延迟超过5分钟",
const reportsData =               "Redis缓存命中率下降至45%",
const reportsData =               "WebSocket连接频繁断开",
const reportsData =               "推送成功率仅为78%"
const reportsData =             ]
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "数据分析服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "200ms",
const reportsData =             "errorRate": "0.12%",
const reportsData =             "availability": "99.85%",
const reportsData =             "requests": "180K",
const reportsData =             "instances": 2,
const reportsData =             "cpuUsage": "58%",
const reportsData =             "memoryUsage": "72%",
const reportsData =             "lastIncident": "2024-05-25",
const reportsData =             "slaCompliance": "99.2%"
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "搜索引擎服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "75ms",
const reportsData =             "errorRate": "0.03%",
const reportsData =             "availability": "99.99%",
const reportsData =             "requests": "2.8M",
const reportsData =             "instances": 4,
const reportsData =             "cpuUsage": "42%",
const reportsData =             "memoryUsage": "65%",
const reportsData =             "lastIncident": "2024-04-28",
const reportsData =             "slaCompliance": "100%"
const reportsData =           },
const reportsData =           {
const reportsData =             "service": "文件存储服务",
const reportsData =             "status": "healthy",
const reportsData =             "responseTime": "45ms",
const reportsData =             "errorRate": "0.01%",
const reportsData =             "availability": "99.99%",
const reportsData =             "requests": "1.5M",
const reportsData =             "instances": 3,
const reportsData =             "cpuUsage": "28%",
const reportsData =             "memoryUsage": "35%",
const reportsData =             "lastIncident": "2024-04-15",
const reportsData =             "slaCompliance": "100%"
const reportsData =           }
const reportsData =         ]
const reportsData =       },
const reportsData =       {
const reportsData =         "titleKey": "performanceTrendAnalysis",
const reportsData =         "title": "性能指标趋势分析",
const reportsData =         "content": "过去30天的关键性能指标变化趋势显示，系统整体性能稳定，但在高峰时段（每日10:00-12:00和19:00-21:00）存在性能压力。通知服务在6月10日开始出现性能下降，支付服务的错误率在6月12日有明显上升。",
const reportsData =         "type": "trend",
const reportsData =         "metrics": [
const reportsData =           {
const reportsData =             "name": "平均响应时间",
const reportsData =             "current": "185ms",
const reportsData =             "previous": "165ms",
const reportsData =             "trend": "+12%",
const reportsData =             "status": "warning",
const reportsData =             "target": "150ms",
const reportsData =             "description": "响应时间较上月增长12%，主要由通知服务拖累"
const reportsData =           },
const reportsData =           {
const reportsData =             "name": "系统吞吐量",
const reportsData =             "current": "15.2K req/s",
const reportsData =             "previous": "14.1K req/s",
const reportsData =             "trend": "+8%",
const reportsData =             "status": "good",
const reportsData =             "target": "12K req/s",
const reportsData =             "description": "系统处理能力持续提升，超出预期目标"
const reportsData =           },
const reportsData =           {
const reportsData =             "name": "错误率",
const reportsData =             "current": "0.23%",
const reportsData =             "previous": "0.08%",
const reportsData =             "trend": "+0.15%",
const reportsData =             "status": "warning",
const reportsData =             "target": "0.1%",
const reportsData =             "description": "错误率上升主要来自支付和通知服务"
const reportsData =           },
const reportsData =           {
const reportsData =             "name": "系统可用性",
const reportsData =             "current": "99.1%",
const reportsData =             "previous": "99.9%",
const reportsData =             "trend": "-0.8%",
const reportsData =             "status": "critical",
const reportsData =             "target": "99.5%",
const reportsData =             "description": "可用性下降主要由通知服务故障导致"
const reportsData =           }
const reportsData =         ],
const reportsData =         "trendData": {
const reportsData =           "responseTime": [
const reportsData =             { "date": "2024-05-15", "value": 158 },
const reportsData =             { "date": "2024-05-20", "value": 162 },
const reportsData =             { "date": "2024-05-25", "value": 165 },
const reportsData =             { "date": "2024-05-30", "value": 168 },
const reportsData =             { "date": "2024-06-05", "value": 172 },
const reportsData =             { "date": "2024-06-10", "value": 195 },
const reportsData =             { "date": "2024-06-15", "value": 185 }
const reportsData =           ],
const reportsData =           "throughput": [
const reportsData =             { "date": "2024-05-15", "value": 13.8 },
const reportsData =             { "date": "2024-05-20", "value": 14.1 },
const reportsData =             { "date": "2024-05-25", "value": 14.3 },
const reportsData =             { "date": "2024-05-30", "value": 14.5 },
const reportsData =             { "date": "2024-06-05", "value": 14.8 },
const reportsData =             { "date": "2024-06-10", "value": 15.1 },
const reportsData =             { "date": "2024-06-15", "value": 15.2 }
const reportsData =           ],
const reportsData =           "errorRate": [
const reportsData =             { "date": "2024-05-15", "value": 0.06 },
const reportsData =             { "date": "2024-05-20", "value": 0.07 },
const reportsData =             { "date": "2024-05-25", "value": 0.08 },
const reportsData =             { "date": "2024-05-30", "value": 0.09 },
const reportsData =             { "date": "2024-06-05", "value": 0.12 },
const reportsData =             { "date": "2024-06-10", "value": 0.18 },
const reportsData =             { "date": "2024-06-15", "value": 0.23 }
const reportsData =           ]
const reportsData =         }
const reportsData =       },
const reportsData =       {
const reportsData =         "titleKey": "resourceUsage",
const reportsData =         "title": "资源使用情况",
const reportsData =         "content": "系统资源使用情况整体合理，但部分服务存在资源瓶颈。通知服务的CPU使用率持续偏高，内存使用量接近阈值。",
const reportsData =         "type": "resources",
const reportsData =         "data": [
const reportsData =           {
const reportsData =             "resource": "CPU使用率",
const reportsData =             "usage": "68%",
const reportsData =             "threshold": "80%",
const reportsData =             "status": "normal",
const reportsData =             "peak": "85%",
const reportsData =             "average": "62%",
const reportsData =             "trend": "+5%",
const reportsData =             "details": {
const reportsData =               "cores": 16,
const reportsData =               "utilization": "10.9/16 cores",
const reportsData =               "topConsumers": [
const reportsData =                 { "service": "通知推送服务", "usage": "22%" },
const reportsData =                 { "service": "搜索引擎服务", "usage": "18%" },
const reportsData =                 { "service": "订单处理服务", "usage": "15%" }
const reportsData =               ]
const reportsData =             }
const reportsData =           },
const reportsData =           {
const reportsData =             "resource": "内存使用率",
const reportsData =             "usage": "72%",
const reportsData =             "threshold": "85%",
const reportsData =             "status": "normal",
const reportsData =             "peak": "89%",
const reportsData =             "average": "68%",
const reportsData =             "trend": "+8%",
const reportsData =             "details": {
const reportsData =               "total": "32GB",
const reportsData =               "used": "23.04GB",
const reportsData =               "available": "8.96GB",
const reportsData =               "topConsumers": [
const reportsData =                 { "service": "数据分析服务", "usage": "6.2GB" },
const reportsData =                 { "service": "通知推送服务", "usage": "5.8GB" },
const reportsData =                 { "service": "搜索引擎服务", "usage": "4.1GB" }
const reportsData =               ]
const reportsData =             }
const reportsData =           },
const reportsData =           {
const reportsData =             "resource": "磁盘使用率",
const reportsData =             "usage": "45%",
const reportsData =             "threshold": "90%",
const reportsData =             "status": "good",
const reportsData =             "peak": "52%",
const reportsData =             "average": "42%",
const reportsData =             "trend": "+2%",
const reportsData =             "details": {
const reportsData =               "total": "2TB",
const reportsData =               "used": "900GB",
const reportsData =               "available": "1.1TB",
const reportsData =               "growth": "15GB/day",
const reportsData =               "partitions": [
const reportsData =                 { "mount": "/", "usage": "35%" },
const reportsData =                 { "mount": "/var/log", "usage": "68%" },
const reportsData =                 { "mount": "/data", "usage": "42%" }
const reportsData =               ]
const reportsData =             }
const reportsData =           },
const reportsData =           {
const reportsData =             "resource": "网络带宽",
const reportsData =             "usage": "35%",
const reportsData =             "threshold": "70%",
const reportsData =             "status": "good",
const reportsData =             "peak": "58%",
const reportsData =             "average": "32%",
const reportsData =             "trend": "+3%",
const reportsData =             "details": {
const reportsData =               "capacity": "10Gbps",
const reportsData =               "inbound": "2.1Gbps",
const reportsData =               "outbound": "1.4Gbps",
const reportsData =               "peakHours": "19:00-21:00"
const reportsData =             }
const reportsData =           },
const reportsData =           {
const reportsData =             "resource": "数据库连接",
const reportsData =             "usage": "156/200",
const reportsData =             "threshold": "180",
const reportsData =             "status": "normal",
const reportsData =             "peak": "189",
const reportsData =             "average": "142",
const reportsData =             "trend": "+12%",
const reportsData =             "details": {
const reportsData =               "maxConnections": 200,
const reportsData =               "activeConnections": 156,
const reportsData =               "idleConnections": 23,
const reportsData =               "connectionPool": {
const reportsData =                 "主库": "89/100",
const reportsData =                 "从库1": "45/50",
const reportsData =                 "从库2": "22/50"
const reportsData =               }
const reportsData =             }
const reportsData =           }
const reportsData =         ]
const reportsData =       },
const reportsData =       {
const reportsData =         "titleKey": "recommendationsAndActionPlan",
const reportsData =         "title": "建议与行动计划",
const reportsData =         "content": "基于分析结果，我们提出以下优化建议和具体行动计划。建议按优先级顺序执行，以最大化系统性能提升效果。",
const reportsData =         "type": "recommendations",
const reportsData =         "recommendations": [
const reportsData =           {
const reportsData =             "priority": "high",
const reportsData =             "item": "立即修复通知服务的性能问题，优化消息队列处理逻辑",
const reportsData =             "deadline": "2024-06-20",
const reportsData =             "assignee": "后端开发团队",
const reportsData =             "estimatedHours": "16小时",
const reportsData =             "impact": "预计可提升系统整体可用性2.5%",
const reportsData =             "steps": [
const reportsData =               "分析消息队列积压原因",
const reportsData =               "优化消息处理批次大小",
const reportsData =               "增加消息处理线程数",
const reportsData =               "实施消息优先级机制",
const reportsData =               "添加消息处理监控告警"
const reportsData =             ],
const reportsData =             "resources": [
const reportsData =               "2名高级后端工程师",
const reportsData =               "1名DevOps工程师",
const reportsData =               "测试环境资源"
const reportsData =             ],
const reportsData =             "risks": [
const reportsData =               "修改过程中可能影响现有推送功能",
const reportsData =               "需要协调多个业务方进行测试"
const reportsData =             ]
const reportsData =           },
const reportsData =           {
const reportsData =             "priority": "high",
const reportsData =             "item": "优化支付服务的错误处理机制，增加重试逻辑",
const reportsData =             "deadline": "2024-06-22",
const reportsData =             "assignee": "支付团队",
const reportsData =             "estimatedHours": "12小时",
const reportsData =             "impact": "预计可降低支付错误率至0.2%以下",
const reportsData =             "steps": [
const reportsData =               "分析支付失败的根本原因",
const reportsData =               "实现智能重试机制",
const reportsData =               "优化第三方支付网关调用",
const reportsData =               "增加支付状态监控",
const reportsData =               "完善支付异常处理流程"
const reportsData =             ],
const reportsData =             "resources": [
const reportsData =               "2名支付系统工程师",
const reportsData =               "1名测试工程师"
const reportsData =             ],
const reportsData =             "risks": [
const reportsData =               "重试逻辑可能导致重复扣款",
const reportsData =               "需要与第三方支付商协调测试"
const reportsData =             ]
const reportsData =           },
const reportsData =           {
const reportsData =             "priority": "medium",
const reportsData =             "item": "扩容通知服务的计算资源，增加2个实例",
const reportsData =             "deadline": "2024-06-25",
const reportsData =             "assignee": "运维团队",
const reportsData =             "estimatedHours": "4小时",
const reportsData =             "impact": "提升通知服务处理能力50%",
const reportsData =             "steps": [
const reportsData =               "申请额外的服务器资源",
const reportsData =               "配置负载均衡策略",
const reportsData =               "部署新的服务实例",
const reportsData =               "验证服务扩容效果",
const reportsData =               "更新监控配置"
const reportsData =             ],
const reportsData =             "resources": [
const reportsData =               "2台云服务器实例",
const reportsData =               "1名运维工程师"
const reportsData =             ],
const reportsData =             "risks": [
const reportsData =               "扩容期间可能出现短暂服务不稳定"
const reportsData =             ]
const reportsData =           },
const reportsData =           {
const reportsData =             "priority": "medium",
const reportsData =             "item": "建立更完善的监控告警机制，增加预警阈值",
const reportsData =             "deadline": "2024-06-30",
const reportsData =             "assignee": "监控团队",
const reportsData =             "estimatedHours": "20小时",
const reportsData =             "impact": "提前发现潜在问题，减少故障时间",
const reportsData =             "steps": [
const reportsData =               "梳理关键业务指标",
const reportsData =               "设置多级告警阈值",
const reportsData =               "配置告警通知渠道",
const reportsData =               "建立告警处理流程",
const reportsData =               "定期回顾告警有效性"
const reportsData =             ],
const reportsData =             "resources": [
const reportsData =               "1名监控工程师",
const reportsData =               "各服务负责人配合"
const reportsData =             ],
const reportsData =             "risks": [
const reportsData =               "告警过多可能导致告警疲劳"
const reportsData =             ]
const reportsData =           },
const reportsData =           {
const reportsData =             "priority": "low",
const reportsData =             "item": "优化数据库查询性能，添加必要的索引",
const reportsData =             "deadline": "2024-07-05",
const reportsData =             "assignee": "DBA团队",
const reportsData =             "estimatedHours": "8小时",
const reportsData =             "impact": "提升查询性能15-20%",
const reportsData =             "steps": [
const reportsData =               "分析慢查询日志",
const reportsData =               "识别缺失的索引",
const reportsData =               "评估索引对写入性能的影响",
const reportsData =               "在低峰期添加索引",
const reportsData =               "验证性能提升效果"
const reportsData =             ],
const reportsData =             "resources": [
const reportsData =               "1名DBA",
const reportsData =               "数据库维护窗口"
const reportsData =             ],
const reportsData =             "risks": [
const reportsData =               "添加索引可能影响写入性能"
const reportsData =             ]
const reportsData =           }
const reportsData =         ]
const reportsData =       }
const reportsData =     ]
const reportsData =   }
const reportsData = };
